CREATE DATABASE myCS;
CREATE USER 'mycsUser'@'localhost' IDENTIFIED BY 'Password123';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'mycsUser'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;